/* empty css                      */import{a as M,S as R,i as n}from"./assets/vendor-C1DvvBV_.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const $="56707604-ad589896bfb00ef829d73b529",O="https://pixabay.com/api/";async function g(o,e=1,i=40){const s={key:$,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:e,per_page:i};return(await M.get(O,{params:s})).data}let x=new R(".gallery a",{captionsData:"alt",captionDelay:250});function y(o,e){const i=o.map(({webformatURL:s,largeImageURL:t,tags:r,likes:a,views:P,comments:q,downloads:E})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${t}">
            <img class="gallery-image" src="${s}" alt="${r}" loading="lazy" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes:</b> ${a}</p>
            <p class="info-item"><b>Views:</b> ${P}</p>
            <p class="info-item"><b>Comments:</b> ${q}</p>
            <p class="info-item"><b>Downloads:</b> ${E}</p>
          </div>
        </li>
      `).join("");e.insertAdjacentHTML("beforeend",i),x.refresh()}function C(o){o.innerHTML=""}const b=document.querySelector(".search-form"),f=document.querySelector(".gallery"),c=document.querySelector(".load-more"),u=document.querySelector(".loader");let d="",l=1;const m=40;let h=0;b.addEventListener("submit",H);c.addEventListener("click",I);async function H(o){if(o.preventDefault(),d=o.currentTarget.elements.searchQuery.value.trim(),!d){n.warning({title:"Caution",message:"Please enter a search query!",position:"topRight"});return}l=1,C(f),p(),L();try{const e=await g(d,l,m);if(h=e.totalHits,!e.hits||e.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(e.hits,f),h>m?S():v()}catch{n.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight"})}finally{w(),b.reset()}}async function I(){const o=l+1;p(),L();try{const e=await g(d,o,m);l=o,y(e.hits,f),A(),l*m>=h?(p(),v()):S()}catch{n.error({title:"Error",message:"Failed to load more images!",position:"topRight"})}finally{w()}}function L(){u&&u.classList.remove("is-hidden")}function w(){u&&u.classList.add("is-hidden")}function S(){c&&c.classList.remove("is-hidden")}function p(){c&&c.classList.add("is-hidden")}function v(){n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}function A(){const o=f.firstElementChild;if(o){const e=o.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
